apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{.Release.Name}}
spec:
  secretName: {{.Release.Name}}
  issuerRef:
    name: {{.Values.dns.certificate.clusterIssuer}}
    kind: ClusterIssuer
  commonName: {{ .Values.dns.hostAdmin}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{ .Values.dns.hostAdmin}}