apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.dnsAuth.host }}`)
      services:
        - name: {{.Release.Name}}
          port: 80
  tls:
    secretName: {{ .Release.Name }}
    domains:
      - main: {{.Values.dnsAuth.host}}
